apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-labs-operator
  labels:
    app: kubernetes-labs-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-labs-operator
  template:
    metadata:
      labels:
        app: kubernetes-labs-operator
    spec:
      serviceAccountName: kubernetes-labs-operator
      containers:
        - name: kubernetes-labs-operator
          image: ghcr.io/skvortsovden/kubernetes-labs-operator:latest
          imagePullPolicy: Always
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-labs-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetes-labs-operator
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["training.dev"]
    resources: ["labs", "labs/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-labs-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubernetes-labs-operator
subjects:
  - kind: ServiceAccount
    name: kubernetes-labs-operator
    namespace: default