apiVersion: training.dev/v1
kind: Lab
metadata:
  name: example-lab-from-file
spec:
  given: ""
  task: "Create a Pod with BusyBox that sleeps for 3600 seconds with name busybox."
  expected: |
    apiVersion: v1
    kind: Pod
    metadata:
      name: busybox
      namespace: default
    spec:
      containers:
      - name: busybox-labs
        image: busybox
        command: ["sleep", "3600"]