apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: labs.training.dev
spec:
  group: training.dev
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                given:
                  type: string
                  description: |
                    YAML manifest(s) defining the "given" resource(s) for the lab.
                givenFile:
                  type: string
                  description: |
                    Path to a file containing the "given" YAML manifest(s) for the lab.
                expected:
                  type: string
                  description: |
                    YAML manifest(s) defining the expected resource(s) for the lab.
                    Provided initially by the teacher; replaced by expectedRef by the operator.
                expectedFile:
                  type: string
                  description: |
                    Path to a file containing the expected YAML manifest(s) for the lab.
                expectedRef:
                  type: object
                  description: |
                    Reference to a Secret storing the expected YAML manifest(s).
                  properties:
                    secretName:
                      type: string
                      description: Name of the Secret containing the expected manifests.
                    key:
                      type: string
                      description: Key inside the Secret data holding the expected YAML.
                  required:
                    - secretName
                    - key
              oneOf:
                - required: ["expected"]
                - required: ["expectedRef"]
                - required: ["expectedFile"]
              oneOf:
                - required: ["given"]
                - required: ["givenFile"]
            status:
              type: object
              properties:
                ready:
                  type: boolean
                  description: Whether the lab resources are ready and valid.
                error:
                  type: string
                  description: Error message if validation failed.
                message:
                  type: string
                  description: A human-readable message indicating the status of the lab.
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Ready
          type: boolean
          jsonPath: .status.ready
        - name: Message
          type: string
          jsonPath: .status.message
        - name: Error
          type: string
          jsonPath: .status.error
  scope: Namespaced
  names:
    plural: labs
    singular: lab
    kind: Lab
    shortNames:
      - lb
